<?php

namespace App\Traits;

trait AuthorizesMarketRequest
{
    public function resolveAuthorization(&$queryParams, &$formParams, &$headers)
    {
        $accessToken = $this->resolveAccessToken();
        $headers['Authorization'] = $accessToken;
    }

    public function resolveAccessToken()
    {
        return 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNkYjIwMGY3MjhlODliOTBlZjRkNmI4NTE4OWU4ZGQwZWU3NGFkMzdlZGRiMDYxMDgwMmQyNGEzNWY1MTM1NzM3YTJlMzQwMzIzZTFjYmJlIn0.eyJhdWQiOiIyIiwianRpIjoiY2RiMjAwZjcyOGU4OWI5MGVmNGQ2Yjg1MTg5ZThkZDBlZTc0YWQzN2VkZGIwNjEwODAyZDI0YTM1ZjUxMzU3MzdhMmUzNDAzMjNlMWNiYmUiLCJpYXQiOjE2MDEzNDI0MDEsIm5iZiI6MTYwMTM0MjQwMSwiZXhwIjoxNjMyODc4NDAxLCJzdWIiOiIxMzkwIiwic2NvcGVzIjpbInB1cmNoYXNlLXByb2R1Y3QiLCJtYW5hZ2UtcHJvZHVjdHMiLCJtYW5hZ2UtYWNjb3VudCIsInJlYWQtZ2VuZXJhbCJdfQ.IusQTI_OCibcP4nwIaH-_B8Curb-3GZ4ykx3gkFGP4uW8GQVVQc1wrYv_5yzTIOsqKC7sdDcRluxbW9xiuLd7mnL8Hg_fm5xs9sPFqVLVzI0OqWs59WwvLLUDhc5Ib4ze4Ea5VsPOMocBVvzIo4yW_6Z6urqTZgBU0E8qWysuUgvAqB-iyEICvScJqUnSLpoSD_QBH-_SdbMOwOLMsA0L0_n_qBq0TPHKIoO9Wwl5UbPYZCpDG60bgeM0iOpb9J9vFuxWnZx-yO_3h5rmpuDowCTUTwrMKC_J9INFhhflN7I8TXUdrKLcE1tIcBtl_OV-oEAzL0aIXsf0PwCvgbGrTlZ7sdbdm3rt36g2uPz4k9a0jDkBMyp66yZtCrlhifPxWJO_YeZc_b-CxlqJXrE3-jjHFShISJJ7iF7dSeRB0ZA5hmYTUDlEXsz-0dYSqu5FpmltuYz2DWdihPSYFuRP7oe1oIHday0rWzG-gFGmkydOc3Pa4GXFnpFSSO3WMNnFFdNpwNlxHECEVmUsEhxiFej4602NGllOqxBkMftUoVKO880tFpS0QExQNjWrsLKjUZNLOSW1aO4qm2SJCFuUopFVDBeZka1JwJSiwLNDBYRk1SPBvXlesNmqVuFPgg_FcG34JxZyh-FCLuaa7oCuOUKpauPo0Rup4qij8Xxak4';
    }
}
